plugins {
    id 'eclipse'
    id 'net.neoforged.moddev' version '1.0.21'
}

version = '1.6.2'
base.archivesName = "concoction-${version}-neoforge (1.21-1.21.1)"

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = "21.1.66"
    ext {
        mc_version = project.findProperty("mc_version") ?: "1.21.1"
        jei_version = project.findProperty("jei_version") ?: "19.21.0.247"
    }

    runs {
        client {
            client()
        }
        server {
            server()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        testproject {
            sourceSet sourceSets.main
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

repositories {
    maven {
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        name = "ModMaven"
        url = "https://modmaven.dev"
    }
}

dependencies {
    implementation 'com.mojang:datafixerupper:1.0.20'

    compileOnly("mezz.jei:jei-${mc_version}-neoforge-api:${jei_version}")
    runtimeOnly("mezz.jei:jei-${mc_version}-neoforge:${jei_version}")
}

task idePostSync {
    doLast {
        println 'Running idePostSync task'
    }
}
